project:
  type: website

website:
  title: "My Workshop"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Slides
        href: slides.qmd
  output-dir: _site

format:
  html:
    theme: cosmo