project:
  type: website
  output-dir: docs

website:
  title: "My Workshop"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Slides
        href: slides.qmd

format:
  html:
    theme: cosmo