project:
  type: website
  output-dir: docs

website:
  title: "RWD Workshop"
  navbar:
    logo: images/logo.png
    left:
      - text: Home
        href: index.qmd
      - text: Slides
        href: slides.qmd

format:
  html:
    theme: [cosmo, theme.scss]